name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests (Jest)
      run: npm run test:unit

    - name: Run smoke test (parser)
      run: npm test

    - name: Build
      run: npm run build

    - name: Lint (optional)
      run: |
        if [ -f package.json ]; then
          echo "No linter configured; skipping."
        fi
