name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true npm ci
      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    # Only run if secrets are configured
    if: ${{ secrets.BASE_URL_CAMARA != '' && secrets.BASE_URL_SENADO != '' }}
    env:
      BASE_URL_CAMARA: ${{ secrets.BASE_URL_CAMARA }}
      BASE_URL_SENADO: ${{ secrets.BASE_URL_SENADO }}
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true npm ci
      - name: Run integration tests
        run: npm run test:integration
