name: Upload ingested to Firebase Storage

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Firebase Storage bucket (ex: legislaplay.appspot.com)'
        required: true
        default: 'legislaplay.appspot.com'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (if secret provided)
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT not set; skipping GCP auth"
            exit 0
          fi
          echo "Secret present; authenticating via google-github-actions/auth"
        # call the official action with uses via a separate step when secret is present
      - name: Call google-github-actions/auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"

      - name: Prepare artifact (zip ingested)
        run: |
          set -e
          mkdir -p artifacts
          TIMESTAMP=$(date -u +%Y-%m-%d)
          ARTIFACT="artifacts/ingested-${TIMESTAMP}.zip"
          echo "Creating $ARTIFACT from resources/data/ingested (if exists)..."
          if [ -d resources/data/ingested ]; then
            zip -r "$ARTIFACT" resources/data/ingested
            ls -lh "$ARTIFACT"
          else
            echo "Directory resources/data/ingested not found in checkout. Aborting." >&2
            exit 2
          fi

      - name: Upload artifact to Firebase Storage (GCS)
        run: |
          set -e
          TIMESTAMP=$(date -u +%Y-%m-%d)
          ARTIFACT="artifacts/ingested-${TIMESTAMP}.zip"
          DEST_BUCKET="${{ github.event.inputs.bucket }}"
          DEST="gs://${DEST_BUCKET}/ingested/$(basename $ARTIFACT)"
          echo "Uploading $ARTIFACT -> $DEST"
          gsutil cp "$ARTIFACT" "$DEST"
          echo "Upload finished"

      - name: Notice missing FIREBASE_SERVICE_ACCOUNT secret
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT secret not set. This workflow will not authenticate to GCP or upload to GCS. The artifact remains attached to this run for manual download."
          else
            echo "FIREBASE_SERVICE_ACCOUNT present; upload should have been attempted."
          fi
